apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 290107119553.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 290107119553.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: ae4c15de
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
